name: build

on:
  push:
    branches:
      - asd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-docker-image:latest .

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.TAG }}
          release_name: "Release v${{ env.TAG }}"
          body: |
            - Docker image: `${{ env.IMAGE_NAME }}:${{ env.TAG }}`
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
