name: build

on:
  push:
    branches:
      - asd

env:
  IMAGE_NAME: snack-lexer-api

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.TAG }}
          release_name: "${{env.IMAGE_NAME}}_v${{ env.TAG }}"
          body: |
            - Docker image: `${{ env.IMAGE_NAME }}:${{ env.TAG }}`
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


